### ISSUE TITLE
Fractal build always concatenates assets. 

### ISSUE THREAD

**Issue by wrux** [netzstrategen/gulp-task-collection#34]
For the style guide we sometimes need a separate stylesheet to customise the style guide theme. 

We cannot currently compile styles with `fractal:build` without concatenation even when using the `--no-concat` or `--concat false` flags.

**Comment by sun** [comment]
https://github.com/netzstrategen/gulp-task-collection/blob/master/tasks/fractal.js does not support parameters currently.

When implementing this, we should add a parameter, because we have at least one implementation (BNN) that requires CSS assets to not be output inline with each component but in the HTML head instead.  A `--concat` flag would be sufficient for them.
